monolog:
    use_microseconds: false
    handlers:

        file:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 1
            channels: ["!event"]
